/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-09 01:30:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;

public final class addform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hi+Melody&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div style=\"margin: 30px 30px;\">\r\n");
      out.write("      <form action=\"shop/addaction.jsp\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("         <table class=\"table table-bordered\" style=\"width: 600px;\">\r\n");
      out.write("            <caption>\r\n");
      out.write("               <b>상품등록</b>\r\n");
      out.write("            </caption>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td style=\"width: 150px; background-color: #66cdaa\">\r\n");
      out.write("                  <b>카테고리</b>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <select style=\"width: 200px;\" name=\"category\" class=\"form-control\" required=\"required\">\r\n");
      out.write("                     <option value=\"피규어\">피규어</option>\r\n");
      out.write("                     <option value=\"선물세트\">선물세트</option>\r\n");
      out.write("                     <option value=\"의상\">의상</option>\r\n");
      out.write("                     <option value=\"악세서리\" selected=\"selected\">악세서리</option>\r\n");
      out.write("                     <option value=\"게임기기\">게임기기</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td style=\"width: 150px; background-color: #66cdaa\">\r\n");
      out.write("                  <b>상품명</b>\r\n");
      out.write("               </td>\r\n");
      out.write("\r\n");
      out.write("               <td>\r\n");
      out.write("                  <input type=\"text\" name=\"sangpum\" class=\"form-control\" style=\"width: 200px;\" placeholder=\"상품명 입력\" required=\"required\">\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td style=\"width: 150px; background-color: #66cdaa\">\r\n");
      out.write("                  <b>상품이미지</b>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <input type=\"file\" name=\"photo\" style=\"width: 300px;\" class=\"form-control\">\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td style=\"width: 150px; background-color: #66cdaa\">\r\n");
      out.write("                  <b>상품가격</b>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  <input type=\"text\" name=\"price\" style=\"width: 120px;\" class=\"form-control\" placeholder=\"가격입력\" required=\"required\">\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td style=\"width: 150px; background-color: #66cdaa\">\r\n");
      out.write("                  <b>입고일</b>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td>\r\n");
      out.write("                  ");

                  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                  String day = sdf.format(new Date());
                  
      out.write("\r\n");
      out.write("                  <input type=\"date\" name=\"ipgoday\" required=\"required\" value=\"");
      out.print(day);
      out.write("\">\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-info\">상품저장</button>\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-info\" onclick=\"location.href='index.jsp?main=shop/shoplist.jsp'\">상품목록</button>\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("         </table>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
