/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-09 01:37:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.NumberFormat;
import data.Dto.ShopDto;
import java.util.List;
import data.Dao.ShopDao;

public final class shoplist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.Dto.ShopDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.Dao.ShopDao");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hi+Melody&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   //$(\"#tabs\").tabs();\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("img.photo {\r\n");
      out.write("   width: 200px;\r\n");
      out.write("   height: 230px;\r\n");
      out.write("   border: 1px solid gray;\r\n");
      out.write("   margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(function() {\r\n");
      out.write("      $(\"a.godetail\")\r\n");
      out.write("            .click(\r\n");
      out.write("                  function() {\r\n");
      out.write("                     var shopnum = $(this).attr(\"shopnum\")\r\n");
      out.write("                     //alert(shopnum);\r\n");
      out.write("\r\n");
      out.write("                     location.href = \"index.jsp?main=shop/detailpage.jsp?shopnum=\"\r\n");
      out.write("                           + shopnum;\r\n");
      out.write("                  })\r\n");
      out.write("   })\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

ShopDao dao = new ShopDao();
List<ShopDto> list = dao.getAllSangpums();

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <ul class=\"nav nav-tabs\">\r\n");
      out.write("         <li class=\"active\"><a data-toggle=\"tab\" href=\"#tabs-1\">전체</a></li>\r\n");
      out.write("         <li><a data-toggle=\"tab\" href=\"#tabs-2\">피규어</a></li>\r\n");
      out.write("         <li><a data-toggle=\"tab\" href=\"#tabs-3\">선물세트</a></li>\r\n");
      out.write("         <li><a data-toggle=\"tab\" href=\"#tabs-4\">게임기기</a></li>\r\n");
      out.write("         <li><a data-toggle=\"tab\" href=\"#tabs-5\">의상</a></li>\r\n");
      out.write("         <li><a data-toggle=\"tab\" href=\"#tabs-6\">악세서리</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"tab-content\">\r\n");
      out.write("         <div id=\"tabs-1\" class=\"tab-pane fade in active\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>전체상품목록</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  NumberFormat nf = NumberFormat.getCurrencyInstance();
                  int i = 0;

                  for (ShopDto dto : list) {
                     //이미지
                     String photo = dto.getPhoto();

                     //20~30까지 난수발생
                     int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"tabs-2\" class=\"tab-pane fade\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>피규어</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  nf = NumberFormat.getCurrencyInstance();
                  i = 0;

                  for (ShopDto dto : list) {

                     if (dto.getCategory().equals("피규어")) {

                        //이미지
                        String photo = dto.getPhoto();

                        //20~30까지 난수발생
                        int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"tabs-3\" class=\"tab-pane fade\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>선물세트</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  nf = NumberFormat.getCurrencyInstance();
                  i = 0;

                  for (ShopDto dto : list) {

                     if (dto.getCategory().equals("선물세트")) {

                        //이미지
                        String photo = dto.getPhoto();

                        //20~30까지 난수발생
                        int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"tabs-4\" class=\"tab-pane fade\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>게임기기</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  nf = NumberFormat.getCurrencyInstance();
                  i = 0;

                  for (ShopDto dto : list) {

                     if (dto.getCategory().equals("게임기기")) {

                        //이미지
                        String photo = dto.getPhoto();

                        //20~30까지 난수발생
                        int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"tabs-5\" class=\"tab-pane fade\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>의상</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  nf = NumberFormat.getCurrencyInstance();
                  i = 0;

                  for (ShopDto dto : list) {

                     if (dto.getCategory().equals("의상")) {

                        //이미지
                        String photo = dto.getPhoto();

                        //20~30까지 난수발생
                        int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <div id=\"tabs-6\" class=\"tab-pane fade\">\r\n");
      out.write("            <p>\r\n");
      out.write("            <table class=\"table table-bordered\" style=\"width: 1000px;\">\r\n");
      out.write("               <caption>\r\n");
      out.write("                  <b>악세서리</b>\r\n");
      out.write("               </caption>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  nf = NumberFormat.getCurrencyInstance();
                  i = 0;

                  for (ShopDto dto : list) {

                     if (dto.getCategory().equals("악세서리")) {

                        //이미지
                        String photo = dto.getPhoto();

                        //20~30까지 난수발생
                        int sale = (int) (Math.random() * 11) + 20;
                  
      out.write("\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <a shopnum=\"");
      out.print(dto.getShopnum());
      out.write("\" style=\"cursor: pointer;\" class=\"godetail\"><img src=\"shopsave/");
      out.print(photo);
      out.write("\" class=\"photo\"> <br> ");
      out.print(dto.getSangpum());
      out.write(" <b style=\"color: red; font-size: 0.8em;\">");
      out.print(sale);
      out.write("%\r\n");
      out.write("                        </b> <span style=\"float: right;\">\r\n");
      out.write("                           <div style=\"color: gray; font-size: 15px;\">\r\n");
      out.write("                              ");

                              int price = (int) (dto.getPrice() + (dto.getPrice() * (sale / 100.0)));
                              
      out.write("\r\n");
      out.write("                              <strike>");
      out.print(nf.format(price));
      out.write("</strike>\r\n");
      out.write("                           </div>\r\n");
      out.write("\r\n");
      out.write("                           <div style=\"color: black; font-size: 16px;\">\r\n");
      out.write("                              ");
      out.print(nf.format(dto.getPrice()));
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                     </span> </a>\r\n");
      out.write("                  </td>\r\n");
      out.write("\r\n");
      out.write("                  ");

                  if ((i + 1) % 4 == 0) {
                  
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("                  ");

                  }
                  i++;

                  }
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
